

Settings

Hi! Here some our recommendations to get the best out of BLACKBOX:

Be as clear as possible

End the question in what language you want the answer to be, e.g: ‘connect to mongodb in python
or you can just
Go to Blackbox
Here are some suggestion (choose one):
Write a function that reads data from a json file
How to delete docs from mongodb in phyton
Connect to mongodb in nodejs
Ask any coding question
send
refresh
Blackbox AI Chat is in beta and Blackbox is not liable for the content generated. By using Blackbox, you acknowledge that you agree to agree to Blackbox's Terms and Privacy Policy
Skip to content
sumit-9767
/
node-todo-cicd

Type / to search

Code
Pull requests
Actions
Projects
Wiki
Security
Insights
Settings
Breadcrumbsnode-todo-cicd
/
Name your file...
in
master

Edit

Preview
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: nodetodo-app
  namespace: default
  labels:
    app: nodetodo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodetodo-app
  template:
    metadata:
      labels:
        app: nodetodo-app
    spec:
      containers:
      - name: nodetodo-app
        image: " 9767264150/nodetodo:latest"
        ports:
          - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: nodetodo-app
  namespace: default
spec:
  selector:
    app: nodetodo-app
  type: LoadBalancer
  ports:
  - name: http
    targetPort: 8000
    port: 80
