---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: nodetodo-app
  namespace: default
  labels:
    app: nodetodo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodetodo-app
  template:
    metadata:
      labels:
        app: nodetodo-app
    spec:
      containers:
      - name: nodetodo-app
        image: " 9767264150/nodetodo:latest"
        ports:
          - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: nodetodo-app
  namespace: default
spec:
  selector:
    app: nodetodo-app
  type: LoadBalancer
  ports:
  - name: http
    targetPort: 8000
    port: 80
